name: base
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-base=4.0
  - python=3.9
  - r-dplyr
  - r-ggplot2
  - r-reshape2
  - r-tidyverse
  - r-shiny
  - pip
  - pip:
    - pandas
    - matplotlib
    - numpy
    - scipy
